### ISSUE TITLE
Comparing two out of many levels in DA analysis

### ISSUE THREAD

**Issue by LenaMayer** [HelenaLC/CATALYST#110]
Dear Helena,

I have a question concerning the differential abundance analysis in diffcyt in the end of your pipeline. 
For example, I have a feature which contains 8 levels:

"aTNF_LPMC" "aINT_LPMC" "aIL_LPMC" "aJAK_LPMC"
"5ASA_LPMC" "Steroids_LPMC" "6MP_LPMC" "HC_LPMC".

Using contrast <- createContrast(c(0, 0, 0, 0, 0, 0, 0, 1)) it would compare my healthy controls (level8) to the anti-TNF treated group (level1). How can I compare level number 8 to each of the other levels seperately?

Moreover, running this, the analysis table gives “NA” as output.

We thus tried the -1 level option. However, once again it only returns NA (see below).

Thanks so much for your help!

contrast <- createContrast(c(0, 0, 1, 0, 0, 0, 0, -1))
da_res1 <- diffcyt(sce, design = DesignMatrix,

contrast = contrast,

analysis_type = "DA", method_DA = "diffcyt-DA-GLMM",

clustering_to_use = "meta10", verbose = TRUE)

using SingleCellExperiment object from CATALYST as input
using cluster IDs from clustering stored in column 'meta10' of 'cluster_codes' data frame in 'metadata' of SingleCellExperiment object from CATALYST

calculating features...
calculating DA tests using method 'diffcyt-DA-GLMM'...

names(da_res1)
[1] "res" "d_counts"
[3] "d_medians" "d_medians_by_cluster_marker"
[5] "d_medians_by_sample_marker"
rowData(da_res1$res)
DataFrame with 10 rows and 3 columns
cluster_id p_val p_adj

1 1 NA NA
2 2 NA NA
3 3 NA NA
4 4 NA NA
5 5 NA NA
6 6 NA NA
7 7 NA NA
8 8 NA NA
9 9 NA NA
10 10 NA NA
table(rowData(da_res1$res)$p_adj < FDR_cutoff)
< table of extent 0 >

**Comment by HelenaLC** [comment]
*Comparing multiple treatment groups against one reference:*

I suggest the following: First, set the reference condition as the first level in your metadata table via
```
md <- ei(sce)
md$condition <- relevel(md$condition, ref = "HC_LPMC")
design <- createDesignMatrix(md, ...)
```

Then, in the design matrix, the coefficient for the healthy controls will be the intercept. Now, you can simply test each coefficient for differences against that reference via

```
for (group in colnames(design)[-1]) {
    contrast <- createContrast(as.numeric(colnames(design) == group))
    da <- diffcyt(...)
    tbl <- rowData(da$res)

    # write results table to .csv
    write.csv(tbl, ...)

    # plot & save results
    png(...)
    plotDiffHeatmap(sce, tbl, ...)
    dev.off()
}
```

*NAs in results:*

While `CATALYST` tries to work together with `diffcyt`, they are not the same package. So I suggest @lmweber can help better with this part. In any case, it'd help if you could post a print out of your design matrix & metadata table (`ei(sce)`) here, so we can understand better what your experimental design looks like. Also, depending on said design, maybe you could try using the other DA method? I've had NAs with some DS methods previously, and switching to another method sometimes work. But again, maybe Lukas can help out here / explain what could be causing this.

**Comment by lmweber** [comment]
Yes I think @HelenaLC has explained the contrast issue above well.

By using `relevel` to set the healthy controls as your reference level, it will make the other coefficients easier to interpret, as the difference between that level and healthy controls. Then, you can use a loop to test each coefficient for differences vs. healthy, as in @HelenaLC 's example.

I'm not sure from this what is causing the NAs, but checking the expression matrix / design matrix / metadata table could help, and otherwise post some additional output here.

**Comment by tammyyyx** [comment]
Hi @HelenaLC ,

Am I understanding it correctly that you suggest setting the coefficient of the reference group as 0 and the difference group we're comparing as 1? What would be the direction of the comparison? I'm asking because I'm not sure whether to set the reference group to 0 or 1  if I want to compare the second and the reference group. According to edgeR, it seems that by setting reference (let's call it A) as 0 and the difference group (let's call it B), the contrast is essentially 0*A+B=B, while by setting the reference as -1 and the difference group as 1 the contrast is -A+B=B-A, so the testing is comparing the overrepresentation of B over A. Is this correct in diffcyt and catalyst too?

**Comment by HelenaLC** [comment]
Apologies for the delay... You might have figured it out by now? - The answer is: It depends. If you set A as the reference factor level, and make a design WITH intercept, coefficients will be relative to this. Then, `c(0, 1, 0)` is correct to test for B vs. A, and `c(0, 0, 1)` to test for C vs. A. Here, the 1st coefficient is the intercept. On the other hand, if you make a design WITHOUT intercept, `c(-1, 1, 0)` is correct to test B-A. Overall, I think this is more of a `edgeR` / model matrix / contrast question and less specifically related to `diffcyt`.

**Comment by tammyyyx** [comment]
@HelenaLC Thanks Helena! I really appreciate the explanation
