### ISSUE TITLE
filterSCE: Loss of metadata

### ISSUE THREAD

**Issue by vivek-verma202** [HelenaLC/CATALYST#116]
Hi again and apologies for so many questions..
I used the following code to remove cells with extreme marker expression:
```
sce <- filterSCE(sce, between(assay(sce["CD3", ], "exprs"), -4, 6))
```
However, after running it, I noticed that the "metadata" slot still had the column names from PBMC_md but with no values:

![image](https://user-images.githubusercontent.com/33168572/84710633-9b7b5c00-af32-11ea-8325-8ba5a75b5c6f.png)

How can I fix this? Thanks..

**Comment by HelenaLC** [comment]
I'm not sure why this is happening... you could try the following 2 to "hacks":

```
# 1) filter as above, then add the metadata table manually 
# while making sure to drop no-longer existent factor levels
sub <- filterSCE(...)
sids <- levels(sub$sample_id)
m <- match(sids, sub$sample_id)
md <- as.data.frame(colData(sub)[m, ])
md <- droplevels(md)
metadata(sub)$experiment_info <- md

# 2) filter the base-R way & update the metadata manually
sub <- sce[, between(exprs(sce)["CD3", ], -4, 6)]
colData(sub) <- droplevels(sub)
md <- metadata(sub)$experiment_info
md <- md[md$sample_id %in% sub$sample_id, ]
md <- droplevels(md)
metadata(sub)$experiment_info <- md
```

- writing the above code from the top of my head, so sorry for any typos!
- a general comment... I don't know if this is the way to go for 2 reasons:
  - you're setting hard cutoffs on the expression. It seams more reasonable to do a data-driven filtering; e.g., removing the lower/upper X% quantiles.
  - I'm not sure what the motivation behind this is in the first place. The DS analysis is performed on aggregation expressions, more specifically, the MEDIAN. This should not be sensitive to extrem expression values of some cells (since the medians means 50% of cells have this value). So, it seems to me a bit ad hock to cut the expression values like this. Especially using hard, objective cutoffs...

**Comment by vivek-verma202** [comment]
Thank-you, Helena! 
The reason why I was "subjectively" cleaning-up the data like that was because of few hundred cells that made the expression density plot look like this:
![image](https://user-images.githubusercontent.com/33168572/84775097-c3a7a100-afac-11ea-970d-167a85576b4e.png)
It's flow-cytometry data from almost completely saturated panel and I guess the super-negative population is due to over-compensation. These artifacts could worsen my signal-to-noise ratio (garbage in, garbage out). Hence, I thought of cleaning the data this way.
Having said that, I guess  "removing the lower/upper X% quantiles" approach could not only be  more objective but also easier to implement. I will try this and will update you, thanks again :)
