### ISSUE TITLE
Scaling option

### ISSUE THREAD

**Issue by bioguy2018** [HelenaLC/CATALYST#127]
Dear Helena,
I was reading the plotExprHeatmap document and the options for parameter scaling. Unfortunately I could not really understand the description for "first and "last"! Would you please kindly explain what does "aggregation" means and does to the datasets before/after trimming in the function? Do you mean all the samples in data are combined together before/ after trimming?

Thank you so much!

**Comment by HelenaLC** [comment]
Apologies if the documentation is not clear enough- let me try to explain:
- aggregation means we summarize the data for each cluster, sample, or cluster-sample (it depends). Where “summarize” means taking eg the mean, median, sum and “the data” means eg counts or expression. By default, we take the median of arcsinh-transformed ion counts. 
- depending on what we are interested in, there are various ways to scale this aggregated data (or “peusobulk” data, because we go from single-cell to something at the cluster, sample, cluster-sample level). 
- Eg, if we want to still retain relative differences, we first scale 0-1, and then aggregate. So markers that were overall low will remain so. If instead we scale “last” (after aggregation), all rows/columns (it depends) will go from 0-1, so we lose relative differences between markers, but might better visualize inter-cluster/sample differences. 
- Along these lines, we use argument “q” to scale between q and 1-q% quantiles. This helps in removing outliers and possibly getting a “cleaner” picture (eg, if 1 box in the heatmap is very high, all other are low, and we don’t see any differences. But “cutting” this value might reveal some priorly indistinguishable differences).
