### ISSUE TITLE
compCytof fails when only one channel is supplied

### ISSUE THREAD

**Issue by loucashwashere** [HelenaLC/CATALYST#142]
First of all thanks for the handy package

I am trying to use the compensation workflow for my CyTOF data. We want to compensate only one particularly troublesome channel spillover (146Di to 162Di). However executing the following fails

```
library(CATALYST)
data(ss_exp)
bc_ms <- c(146)
sce <- prepData(ss_exp)
sce <- assignPrelim(sce, bc_ms, verbose = FALSE)
```
```
Error in apply(bcs, 2, order, decreasing = TRUE) : 
  dim(X) must have a positive length
```
Upon quick inspections might be related to trying to order the markers in the .get_ids() function, since only one value is supplied
`bc_orders <- apply(bcs, 2, order, decreasing = TRUE)`

Thanks for any help
Lucas

**Comment by HelenaLC** [comment]
Question before digging deeper- Does your data use the same panel as `ss_exp`? Meaning, this is example data from the package but it is not meant to be applicable to *any* dataset. The accuracy of the spillover estimates obtained from the signel-stained beads in `ss_exp` for your data will depend on this: Do you have the same masses/metals and thus the same spillover interactions?

**Comment by loucashwashere** [comment]
No. I used ss_exp here to provide a reprex. In reality we have our one single stained bead control (stained with 146Di), using of which results in the same error msg

**Comment by HelenaLC** [comment]
Okay, so while this is a "bug" in the code in the sense that subsetting a single columns from the barcode expression matrix gives a vector, which could be resolved via `matrix[, columns_to_keep, drop = FALSE]`, there's a more general issue with your  approach.

Briefly put, the single-cell debarcoding algorithm (Zunder et al.) implemented in `CATALYST` works by 
1. assign each event to the barcode ID where barcode channels have the highest expression
2. compute the distance between the highest negative barcode, and lowest positive barcode channel (where negative means this channel should not be positive for this barcode)
3. label events unassigned when this distance is below a threshold (plus filtering on Mahalanobis distances to remove outliers)

Now, if you run `assignPrelim` using a single barcode channel (146), there is no negatives, and the whole approach fails. I.e., once we identify events with highest expression in 146, we have nothing to compare that against. So it really doesn't make sense to do this.

**Comment by vtosevski** [comment]
Hello everyone!
Interesting discussion and I am compelled to join, not least for the fact that Lucas is a team member so I feel the problem myself.
I have not appreciated before that `CATALYST` uses Zunder et al debarcoding for compensation. I am not familiar with the "mechanics" of how debarcoding is accomplished, but the problem at hand here is - can one use CATALYST to compensate a *single* spillover source, i.e. having only one single stained control? I appreciate your description @HelenaLC and the reasoning as to why it fails in this case. But compensating a single source of spillover makes **experimental sense**. If one uses antibody-capturing beads for compensation, the "negative" beads will anyhow generate zero signal (as they're not stained). So how does one accomplish the task at hand here?

**Comment by HelenaLC** [comment]
Yes, so under the hood, `CATALYST` uses the SCD algorithm to deconvolute the single-stained beads, using essentially a diagonal matrix as the debarcoding scheme (i.e., we want a bead to be positive in 1 channel, and negative in all others). I thought at the time that was a "smart" way to do it. Then again, we have limited understanding of the biology/experimental details here. 

So the question that comes to my mind is: When you stain for a single barcode channel, do you expect all other channels will be 100% negative, for sure? 
- If yes, "debarcoding" would just mean "if barcode x > 0 -> assign to x". 
- If no, a possible solution would be dynamic cutoff, based on the assumption that the barcode channel stained for should be much more positive than all others.

**Comment by vtosevski** [comment]
Hi Helena,

Sorry for dropping the exchange here, I hope you're still eager to solve this. To your questions...

> When you stain for a single barcode channel, do you expect all other channels to be 100% negative, for sure?

Depends what you mean. If I stain a single channel (on beads), I expect that one to show some signal (specific signal) while others would be either zero or something, in which case "something" would be a spillover. I guess here we can simplify the framework and say that, in absence of the measured autofluorescence, cytof essentially measures 0 if there's no spillover.

> Can we be 100% sure the staining worked for all beads?

That's a though question. Most of the time the staining "just works" on the beads. Without specific staining, beads will generate no signal. Whether one sees suboptimal signal should be a problem of the experimenter, not the method, don't you think?

Look forward to hearing from you.

**Comment by votti** [comment]
Also chipping in:
- I think if the experimenter really only injects 'single stained beads' I would argue the heuristic: "if barcode x > 0 -> assign to x"  should do. In particular as the spillover estimation should be fairly robust, so if there are some beads which are negative for whatever reason, this should not affect the overall estimation as long as staining worked for the majority of beads.

In such a case the algorithm further needs to be adapted to assume '0' background staining per channel, as the background is usually estimated from all other bead populations that are not expected to affect a channel.

- Experimentally  I would not recommend to do such a 'single stained' beads experiment as this does not allow to estimate and account for channel specific background which is part of the standard spillover estimation. So to me it would make sense to routinely mix a second 'single stained' beads reference in that would allow to estimate background.
But then again I think CATALYST should also support a 'sub-optimal' workflow with only a single bead population.

**Comment by vtosevski** [comment]
> Experimentally I would consider such a 'single stained' beads experiment suboptimal as this does not allow to estimate and account for channel specific background which is part of the standard spillover estimation.

But how do you estimate this background signal in CATALYST? Is it better/more precise than assuming zero in a single-reagent setup? CyTOF measures no intrinsic signal of the unstained beads so 0 is a fair assumption. I am not aware of any better way of estimating meaningful antibody-specific background signal on the negative population, which is what you conceptually need for precise spillover estimation.
I am carefully expanding this discussion because we wanted to "hack" the system initially and Lucas made in silico second single stained control, just to have CATALYST working around this problem. It was one channel with "signal" and all others perfect zero - we thought this should be fine and safe. To our surprise, CATALYST introduced some compensation in other channels in response (!?). Happy to additionally collect your thoughts on this "hack" and its results.

To make a full circle, I would love to see CATALYST handling also this special case of single-reagent compensation.

**Comment by votti** [comment]
The background signal estimation is described in our original paper:

"The expected background signal in these channels was computed as the
median (or trimmed mean) signal of events that are i) negative in the
channels i and j for which the spillover is investigated, ii) not assigned
to interacting channels, and iii) not unassigned. These medians were
indicated as mi j and mi i , and subtracted:"

There are some exceptions where cyTOF has definitely not perfect 0
background, in particular channels affected by background contaminations
such as Xenon, Barium and the like (plus their +1, isotopic and +16
spillover channels).

I remember having once dealt with compensation with Tellurium probes that
are affected by Xenon and Xenon spillover - in such cases this background
estimation is crucial.

Anyways, I think single experiments and assuming 0 background is usually
fine in practice, but having more than one stain together is theoretically
more accurate as it allows to correctly account for background.

**Comment by HelenaLC** [comment]
@vtosevski, not sure if I was super clear in my earlier responses... the key issue I see from a computation perspective is: Even if we assume (hypothetically) the bead staining is perfect and all else is zero- this is really never the case. I think mainly because the CyTOF adds random noise to the counts (so they are not exactly 0)? 

I did a little test on the `ss_exp` example dataset in `CATALYST`. The plot below shows the mean expression in each channel of events NOT assigned to that barcode. We can see nicely 

i. the +16 spillover (which I guess would disappear in a single-staining scenario), and
ii. even non-spill affected channels are rarely 0 exactly

![image](https://user-images.githubusercontent.com/14542264/99091142-c34d1980-25cf-11eb-8d49-9a0835eb944f.png)

This leads, in my opinion, to a non-straightforward issue: How do we decide what is negative and what is positive without something to compare against? I think adding a mock channel as you did in your hack could solve this, and this could be a possible solution for `CATALYST` to do internally (so you don't have to) when there is only 1 barcode channel specified. The question then is only how to set it up...

**Comment by HelenaLC** [comment]
Assuming this is resolved for now...
