### ISSUE TITLE
questions about mass channels in compensation workflow

### ISSUE THREAD

**Issue by calpiko** [HelenaLC/CATALYST#148]
Hi Helena,

I'm new to cytof data analysis and have some very naive questions about the compensation workflow. Thanks in advance for your time.

I was following this part:
specify mass channels stained for & debarcode
bc_ms <- c(139, 141:156, 158:176)
sce <- prepData(ss_exp)
sce <- assignPrelim(sce, bc_ms, verbose = FALSE)
sce <- applyCutoffs(estCutoffs(sce))

when I tried  a subset of mass channels from my dataset it worked fine; but when I included all mass channels stained for I got this error: 
Error in base::colMeans(x, na.rm = na.rm, dims = dims, ...) : 
  'x' must be an array of at least two dimensions

I was wondering if it has something to do with some specific channels so I tried another subset complementary to the first subset I did, but this worked too.  My general question is why did this error occur and how should the input numeric vector be determined?

thanks!

**Comment by HelenaLC** [comment]
This error came up in #142. There, however, the issue was caused by `bc_ms` being of length one: By subsetting like this `matrix[rows, ]` vs. `matrix[rows, , drop = FALSE]`, which gives a vector, `colMeans` fails as it expects a matrix. Here, I'm not sure... Do you maybe have the code as well as the `colnames(sce)` for your data? From the above, I cannot tell what is causing this.

When `bc_key` is not a `data.frame`, it should be "a vector of numeric masses corresponding to barcode channels", meaning, the masses of the channels that where stained for (as you said above).
