### ISSUE TITLE
Adding function to plot histograms

### ISSUE THREAD

**Issue by poconnel3** [HelenaLC/CATALYST#149]
Hi Helena, 

This is not so much of an issue as a request to add more functionality to CATALYST. I (and probably others) am trying to generate histogram density plots of various markers. Specifically, plotting a marker on a cluster and overlaying based on a metadata parameter of choice. While the function to make ridge plots is functional, it has limited functionality and is really not the same as overlaying histograms like one would in FlowJo or the like. I have a very ugly and inefficient workaround I am using right now, but integrated functionality into the package would be a much more elegant solution. Is there anyway to make this happen in the future?

As an aside, thank you very much for always being so responsive and helping to constantly improve this package for the community!

**Comment by HelenaLC** [comment]
Unfortunately I’m not sure I really get it... Could you be a bit more specific? Maybe you have some example screenshot from flowJo or a plot you made that I can look at?

Thanks for the kind words, I appreciate it. This has been a long ongoing and at times stressful process. But the community using and appreciating the package is the best reward!

**Comment by SamGG** [comment]
@poconnel3 did you look at [stacked density plots in ggcyto](https://www.bioconductor.org/packages/release/bioc/vignettes/ggcyto/inst/doc/ggcyto.flowSet.html#stacked_density_plot)?

**Comment by poconnel3** [comment]
@HelenaLC  something like this from ggcyto: 
![Screen Shot 2020-10-07 at 9 33 40 AM](https://user-images.githubusercontent.com/67804612/95337865-4ae09380-0880-11eb-8216-2634ff0fca74.png)

Is there a way to call this directly from data in a CATALYST SCE object?

@SamGG  yes, that is what I am trying to do. Just not sure how to get the data simply from the SCE to ggcyto. 

Thanks!

**Comment by SamGG** [comment]
With Helena and the flowCore team you will certainly get a nice solution.

I forget to mention the work of @DillonHammill https://github.com/DillonHammill/CytoExploreR that may help.

Currently, I believe that developments should converge/capitalize on these packages for such a need in order to avoid dispersing community forces and attention.

Best.

**Comment by HelenaLC** [comment]
Fully agree with the above. Implementing already existent functionality seems a duplicated and thus wasted effort, especially given the large flexibility already provided by both `CATALYST` and `ggcyto`. 

Besides, you can easily create ANY plot using `ggplot2` from a `data.frame` that contains expressions and cell metadata, and can be constructed via a one-line command such as: 

`ggdf <- data.frame(colData(sce), t(assay(sce, "exprs")), check.names = FALSE)`

With that, the above plot for example would be:

`ggplot(ggdf, aes_string("FSC-H", fill = "sample_id")) + geom_density()`
*the `aes_string` isn't necessary but I can't get back-ticks to work...

All that is to say, there is lots of infrastructure out there, but it is generally straight forward to make plots that fit your specific need because package x cannot do it, or for e.g. publication.
