### ISSUE TITLE
Error in prepData transform

### ISSUE THREAD

**Issue by MartijnVNL** [HelenaLC/CATALYST#156]
Hi Helena,

I've recently started using Catalyst to analyse my FACS data and I've run into a problem. I'm using FlowVS to calculate custom cofactors for each channel and apply arcsinh transformation with those cofactors. This transformed data is stored in a flowSet, which I then use as input for Catalyst. Since that data is already transformed I don't want it to be transformed again. In the prepData function I therefore set transform = FALSE (sce=prepData(fs.VS, panel, md, features=markers_CF, FACS = TRUE, transform = FALSE). However, when I subsequently try to run UMAP (or any other analysis) I get the following error: Error in .check_assay(x, assay) : sum(y == assayNames(x)) == 1 is not TRUE. The problem does not seem to be in the flowSet, because when I set transform = TRUE UMAP runs without problems. The only difference (as far as I can see) is that when transform = TRUE the "assays" parameter in sce consists of both "counts" and "exprs", whereas when transform = FALSE there is only "counts". So I was wondering if there is a fix for this.

Kind regards,

Martijn

**Comment by HelenaLC** [comment]
Easy to fix! You did everything correct and also pin-point the problem: The default to `runUMAP`(and majority of all other functions)  is `assay = "exprs"`. This, as you said, doesn't exist when `prepData` was run with `transformation = TRUE`. Since your data (now in assay `counts`) already contains expression values though, you can simply rename the assay. Then, all downstream functions expecting expression values will run.

```
# rename assay "counts" to "exprs"
assayNames(sce)[1] <- "exprs"
```

**Comment by MartijnVNL** [comment]
Thanks so much! Worked perfectly
