### ISSUE TITLE
inspect antigens contribution to UMAP dimensions

### ISSUE THREAD

**Issue by calpiko** [HelenaLC/CATALYST#171]
Dear Helena, 

  Is there a way to look at antigens' contribution to different dimensions in UMAP?

Thank you.

**Comment by HelenaLC** [comment]
While there are PC loadings in PCA that give the contribution (weight) of each feature in each PC, a similar measure doesn't exist / is more challenging for UMAP and other non-linear dimensionality reduction methods, e.g. t-SNE. However, you might find the article below useful:

From [Angerer et al.](https://academic.oup.com/bioinformatics/article/36/15/4291/5811230): "with no linear relation between gene and embedding coordinate, there is no way to extract the identity of genes driving any cell’s position in the low-dimensional embedding" ... ''[...] We introduce the concepts of local and global gene relevance to compute an equivalent of principal component analysis loadings for non-linear low-dimensional embeddings. *Global gene relevance* identifies drivers of the overall embedding, while *local gene relevance* identifies those of a defined sub-region."

**Comment by SamGG** [comment]
@calpiko Could you elaborate what you want to do: if you have the contribution of the antigens to each of the two dimensions of a UMAP, how will you interpret it? IMHO, the UMAP is better interpreted as a radial plot/visualisation, ie none of the two dimensions of the UMAP are useful because by definition the goal of the non-linear dimension reductions is to unfold the dataset. Even in a PCA plot, sometimes the interesting axes are rotated from the resulting axes from the PCA. Your thought interests me...
