### ISSUE TITLE
markers after clustering

### ISSUE THREAD

**Issue by antoine4ucsd** [HelenaLC/CATALYST#172]
Hello
I am using the CATALYST::cluster function on my flow data.
My panel includes 13 markers
`panel$fcs_colname
 [1] "Alexa Fluor 700-A" "PE-CF594-A"        "APC-H7-A"          "BV421-A"           "BV711-A"           "BV786-A"           "BV605-A"           "PE-Cy7-A"         
 [9] "BV650-A"           "APC-A"             "PE-A"              "PerCP-Cy5-5-A"     "Alexa Fluor 488-A"`

and are present in my flwoset object
`
all(panel$fcs_colname %in% colnames(fs1))
[1] TRUE
`
but after running 
`
sce <- CATALYST::cluster(sce, features = NULL,
               xdim = 10, ydim = 10, maxK = 20, seed = 1234)
`
I only have 11 markers left....

DataFrame with 11 rows and 4 columns
            channel_name marker_name marker_class used_for_clustering
             <character> <character>     <factor>           <logical>
CD3    Alexa Fluor 700-A         CD3        type                 TRUE
CD4           PE-CF594-A         CD4        type                 TRUE
CD8             APC-H7-A         CD8        type                 TRUE
HLA-DR           BV421-A      HLA-DR        type                 TRUE
CD38             BV711-A        CD38        state                TRUE
CCR7             BV786-A        CCR7        type                 TRUE
CD45RA           BV605-A      CD45RA        type                 TRUE
PD-1            PE-Cy7-A        PD-1        state                TRUE
TIM-3            BV650-A       TIM-3        state                TRUE
CD73       PerCP-Cy5-5-A        CD73        state                TRUE
CD160  Alexa Fluor 488-A       CD160        state                TRUE

I am probably missing something obvious... can you help?

thank you!

**Comment by HelenaLC** [comment]
Hard to read the output above - but if I'm not mistaken, the missing channels are APC-A and PE-A. These are the only ones not containing any numbers. So my guess is this:

- By default, prepData() will retain only mass channels in the assay data. All none mass channels (e.g. in CyTOF, these are time and event length) are moved to the int_colData().
- Thus, when you construct the SingleCellExperiment, the object already has only 11 features, and this is not the result of running cluster().
- Now, since this is FACS data, there are no mass and no-mass channels, and we want to retain all parameters.
- To enforce this, you should run prepData(..., FACS = TRUE). All 13 markers will then remain in the main assay data.

**Comment by antoine4ucsd** [comment]
That sounds promising! I will give it a try and confirm asap.
Thank you!

a

**Comment by HelenaLC** [comment]
solved; see [Bioc support forum](https://support.bioconductor.org/p/p133688/)
