### ISSUE TITLE
Differential expression analysis

### ISSUE THREAD

**Issue by nkingston2021** [HelenaLC/CATALYST#179]
I'm using the diffcyt package to perform differential expression analysis on my CATALYST daFrame object and have some questions/issues with regards to diffcyt-DS-limma versus diffcyt-DS-LMM.
1. The diffcyt-DS-LMM method will not calculate p-values for me. It returns "NA" for all the p-values when I look at the results via topTable, though there is no error message that pops up. On the other hand, the diffcyt-DS-limma method does calculate p-values for me.

For diffcyt-DS-LMM method, I made a formula and contrast matrix (as outlined on http://bioconductor.org/packages/release/workflows/vignettes/cytofWorkflow/inst/doc/cytofWorkflow.html#differential-analysis-of-marker-expression-stratified-by-cell-population). Furthermore, I've been using the diffcyt-DA-GLMM method to look at differential abundance with no issue.

2. When do you recommend using diffcyt-DS-limma vs diffcyt-DS-LMM for expression analysis on a CATALYST daFrame object? (Diffcyt-DS-limma is used here: https://www.bioconductor.org/packages/3.11/bioc/vignettes/CATALYST/inst/doc/differential.html#plotdiffheatmap-heatmap-of-differential-testing-results)

**Comment by HelenaLC** [comment]
1. While `CATALYST` and `diffcyt` try to interact with each other, they are separate packages. I recommend posting this issue here https://github.com/lmweber/diffcyt as @lmweber might be more knowledgeable to answer this.

2. You mentioned `daFrame` object. This class has been outdated for a couple years now. I **highly** recommend updated your software to the current version as there has been an extensive amount of bug fixes and feature additions over the past.
