### ISSUE TITLE
marker intensity and clustering

### ISSUE THREAD

**Issue by antoine4ucsd** [HelenaLC/CATALYST#185]
Hello helena
thank you for your pipeline. really amazing
I am struggling with one specific issue regarding expression of Ki67 marker in my panel. as shown in the density expression plot. I doubt Ki67 is really informative to identify the clusters ...
I am using a kmean approach to assign 'positivity' /'negativity' or 'low' vs 'high' for each cluster/marker. Obviously it is will not be appropriate with the dense ki67 profile. I wonder if there would be a way to look deeper into this marker (when looking at it with  FlowJo, I do expect to have 0-5% ki67 positive cells per sample) but I would like to assign each cluster to a KI67 pattern (negative or positive...).
not sure if it makes sense...
THANK YOU!
![_2_Menopause function MarkerDensityplots cd3pos 2021-01-02](https://user-images.githubusercontent.com/18502631/106653104-391bae00-654b-11eb-880b-692462ed5c77.png)

**Comment by HelenaLC** [comment]
Hey Antoine, thanks for the kind words.

Hm, I am not sure I understand exactly what you're looking for. Here are my thoughts:

1. What's your motivation to use k-means instead of a more "sophisticated" approach? E.g. there are clustering methods that would cluster cells based on the expression profiles (all markers), instead of looking at each marker in a binary (neg./pos.) way. `CATALYST` uses `FlowSOM`, but other frameworks can be used and incorporated in the workflow as well (see vignette).

2. While the distributes are useful, I find looking at aggregated measures "easier to digest" (e.g. marker means/medians by cluster or cluster-sample). A useful visualisation to identify clusters low/high in KI67 and/or also inspect the inter-sample variability is `plotPbExprs()`. Here are two examples:


```
library(CATALYST)

data(PBMC_fs, PBMC_panel, PBMC_md)
sce <- prepData(PBMC_fs, PBMC_panel, PBMC_md)
sce <- cluster(sce, verbose = FALSE)

# panels = clusters
# x-axis = markers
# points = samples
plotPbExprs(sce, 
    k = "meta12", 
    features = "type", 
    assay = "exprs", 
    fun = "mean",
    color_by = "sample_id",
    facet_by = "cluster_id")
```
![image](https://user-images.githubusercontent.com/14542264/106887104-fab9f680-66e4-11eb-9e83-e9a91070c2f0.png)

```
# panels = markers
# x-axis = clusters
# points = samples
plotPbExprs(sce, 
    k = "meta12", 
    features = "type", 
    assay = "exprs", 
    fun = "mean",
    color_by = "condition",
    group_by = "cluster_id",
    facet_by = "antigen",
    ncol = 5)
```
![image](https://user-images.githubusercontent.com/14542264/106887053-e8d85380-66e4-11eb-82a7-ad40de0650e8.png)

Even more clearly, expression difference in the marker of interest could be seen in a heatmap of clusters x samples:

```
plotExprHeatmap(sce,
    features = "CD3",
    by = "both",
    k = "meta12")
```
![image](https://user-images.githubusercontent.com/14542264/106887273-38b71a80-66e5-11eb-9996-d6ab45a6e1bc.png)

**Comment by antoine4ucsd** [comment]
Thank you Helena
The first plot may effectively be more appropriate to discriminate differences between clusters or samples for this specific marker. I am aware of the clustering methods you are referring to. Here, I wanted to end up with a discrete classification (pos/neg) at the cluster level. I will get back to you with another plot to illustrate my objective 

Thank you so much for always being responsive 

a

**Comment by SamGG** [comment]
Hi,
From the profile of Ki67, I can't say that there is any pos/neg difference among the clusters.
All Ki67 profiles are located at 1. The CD4 and CD8 profiles are also odd IMHO. What kind of scaling did you apply?
I am not sure wether FlowSOM could detect a difference with so nicely aligned Ki67 profiles.

**Comment by HelenaLC** [comment]
Could you post a plot so I can see what you're talking about?

**Comment by poconnel3** [comment]
I agree with SamGG. I have analyzed data w/ CATLYST the way you are interested in. You have to manually gate out the positive population of interest in FlowJo first and make a boolean to get the negative cells. Now you import both the positive and negative fcs files for that marker into CATALYST. You then add a column to your metadata sheet annotating each FCS file based on positive or negative expression of your marker. Now you can separate your cells in CATALYST by absolute positive or negative expression of that marker. 

But from your image, it appears all your cells are ki67 negative unless you transformed your data wrong.

**Comment by antoine4ucsd** [comment]
seems like an interesting approach.
so you just 'filter out' the negative fcs if you only want to focus on the positive?

thanks

**Comment by poconnel3** [comment]
> seems like an interesting approach.
> so you just 'filter out' the negative fcs if you only want to focus on the positive?
> 
> thanks

Yup, Just filter the sce by the new metadata parameter.

**Comment by antoine4ucsd** [comment]
and what about doing a first clustering in CATALYST with ONLY CD3  (for example) and save the fcs after filtering out the 'negatives' (kmeans with k=2, assuming 2 categories: pos or neg)

**Comment by poconnel3** [comment]
> and what about doing a first clustering in CATALYST with ONLY CD3 (for example) and save the fcs after filtering out the 'negatives' (kmeans with k=2, assuming 2 categories: pos or neg)

I mean I guess it could work. Depends on the expression pattern though. CD3, yea, it should separate them, your Ki67, not likely since it is a unimodal distribution. 

Using FlowJo (or any other GUI-based FACS analysis software) is really going to be a lot quicker. Or if you are good w/ FlowCore you can apply cutoff w/ that.

**Comment by antoine4ucsd** [comment]
Thank you!

--
a

**Comment by HelenaLC** [comment]
Is this resolved? If so, please close the issue :) Or else let me know if there's still something unresolved/unclear. Thanks!

**Comment by antoine4ucsd** [comment]
sorry Helena
I actually worked on it in the last week and made some progress. I will close for now and update you as soon as I have consolidated results. thank you all for the suggestions!
