### ISSUE TITLE
Debarcoded files to FCS

### ISSUE THREAD

**Issue by natsume17** [HelenaLC/CATALYST#188]
Apologies for a rather simple question, I'm relatively new to R.
After debarcoding, I am trying to write these to FCS files. 

```
# run debarcoding
sce <- prepData(sample_ff)
sce <- assignPrelim(sce, sample_key)
sce <- applyCutoffs(estCutoffs(sce))
# exclude unassigned events
sce <- sce[, sce$bc_id != 0]
# convert to 'flowSet' with one frame per sample
(fs <- sce2fcs(sce, split_by = "bc_id"))


```

```

ids <- fsApply(fs, identifier)
for (id in ids) {
    ff <- fs[[id]]                     
    fn <- sprintf("sample_%s.fcs", id) 
    fn <- file.path("...", fn)       
    write.FCS(ff, fn)                 
}


```
I'm just a bit unclear as to what to plug in what to where in the above (aside from the file path). Whatever I enter, it will return a debarcoded FCS file to one random sample. 

Thank you very much!

-N
```

**Comment by SamGG** [comment]
At the end of debarcoding (the first chunk), fs is a set of flowframes, each being a representation of a FCS file in R.
The second chunk aims at writing each flowframe of the set to disk, using its internal identifier as file name.
If you succeeded in running the 1st chunk, then just set a correct path instead of "..." and run this chunk.

**Comment by natsume17** [comment]
Yes I see, that obviously did the trick. Many thanks in answering such a naive question!

Best
N
