### ISSUE TITLE
Removing batch effect 

### ISSUE THREAD

**Issue by Behind42** [HelenaLC/CATALYST#201]
Hello, 

First, thank you very much for this package and the workflow, very helpful to analyze CyTOF datasets in my lab. 

It's been now few months since I'm using it but for the first time, I have an analysis to perform from multiple batches. 
I would like to have your thoughts on how to handle possible batch effect because as far as I know, there is no function in CATALYST itself to handle this?

Would you prefer to use iMUBAC, CytoNorm or others? 
To be more specific, I have 4 batches but no controls in all of the batches and they are not equilibrate so I was looking for iMUBAC but it seems that the compatibility with a subsequent analysis using CATALYST after batch-effect correction is not that easy.

Thank you in advance and sorry if the question has been asked before I looked for it but didn't find the best answer. 

Quentin

**Comment by SamGG** [comment]
Hi,

iMUABC is based on Harmony and does not require any control/reference/replicate. CytoNorm, cytofBatchAdjust and some others require such a reference between batches. I would tried to build such a reference by sampling and merging all the samples of each batch. As you raise the point (IIUC "equilibrate"), I would balance the type of samples in each batch so that each group of patients is correctly represented: if in batch I there are 10 patients group A and 50 patients group B, then sample 5k cells of each FCS of group A and 1k cells of each FCS of group B, which leads to 100k cells. Then the batch correction would adjust with the files of 100k cells.

I would first carry out his adjustment with cytofBatchAdjust, but having modified its code, I am biased towards it. The main goal batch correction is to scale each channel to adjust the dynamic range to the other batch. IMHO the scaling has to be linear, which might not be always the case with CytoNorm. CytoNorm clusters cells and then normalize each channel for each cluster IIRC, but I don't see a good reason for having a different correction for each channel of each cluster. Whatever, I think the most important point is to get a positive anchor/pop to correctly estimate the scaling. That's my personal view.

Hamony seems to do some god job, but I am unsure about the scalability of the scRNAseq approaches. Here are 2 benchmarks concerning scRNAseq if you want to try those.
* [A benchmark of batch-effect correction methods for single-cell RNA sequencing data](https://pubmed.ncbi.nlm.nih.gov/31948481/)
* [Flexible comparison of batch correction methods for single-cell RNA-seq using BatchBench](https://pubmed.ncbi.nlm.nih.gov/33524142/)
 
Finally, I think your interesting should deserve a larger, which you will find on cytoforum.

Let us know about your findings.

Best,
Samuel

**Comment by Behind42** [comment]
Hi, 

Thank you for your answer, I will try what you suggest and come back here with the result. 

Quentin

**Comment by HelenaLC** [comment]
Closing for now to keep track of unresolved issues better; feel free to re-open & share you’re experiences.

**Comment by purisuto** [comment]
There is a recently-released batch correction method called cyCombine, which I have used to good effect. https://github.com/biosurf/cyCombine

Currently, I have found that it is easier to save the output of cyCombine as .fcs files (use `df2SCE`, `sce2fcs` and `write.FCS`), and then reimport into CATALYST.  Be aware of whether the data needs to be transformed or not at each stage.
