### ISSUE TITLE
pbMDS error when only 1 factor

### ISSUE THREAD

**Issue by gcohenJH** [HelenaLC/CATALYST#217]
When trying to use the pbMDS function with only 1 factor in my data, and using that factor for `color_by` or `label_by` I get the following error from ggplot:

`Error in FUN(X[[i]], ...) : object 'test_factor' not found`

This is a very similar issue to #159, but I believe I have found the problem. On line 110 of the pbMDS.R function  `df <- cbind(df, colData(x)[m, i])`, if you have only 1 factor set, the column added to the dataframe by cbind is named `colData(x)[m, i]`. When ggplot then looks for the column you set for `color_by` or `label_by`, it can't find it since it's named `colData(x)[m, i]`. If you have multiple factors, the columns in the dataframe are added correctly, and the function works as intended.

I may have had a similar issue using other functions, but I have only confirmed the issue with pbMDS.

**Comment by HelenaLC** [comment]
Thanks for catching this! I have resolved this issue by setting `drop = FALSE` in the `colData` subsetting so that a `DFrame` (with names) is returned independent of where `i` contains one or many columns. The fix is in branch `RELEASE_3_13` on GitHub, and should be available through BioC in a couple days. Do let me know if a similar issue comes up in other functions.
