### ISSUE TITLE
heatmap font size

### ISSUE THREAD

**Issue by bioguy2018** [HelenaLC/CATALYST#219]
Dear  Helena,
I would like to change the heatmap text size and I realized  it's complexheatmap object but unfortunately the function doesn't allow the global variable to change the size or edit the text. How can I achieve this goal?

Thanks you

**Comment by HelenaLC** [comment]
I've gone through lots of pain regarding this... To my knowledge, there is no way to globally change the font size (e.g., with `ggplot2`, this can be done via `theme_x(base_size = ...)`). You'll have to set the fonts individually for each element (row/column names/titles, legend labels/titles etc.) in side of `draw()`; see `?draw` for the long list of options. Note that, it might not be necessary to set all options, but only the ones that actually appear in the heatmap you're drawing.

**Comment by bioguy2018** [comment]
Thank you so much for your quick response! 
I will try the draw function! for now I just saved the heatmap as an object to access the heatmap matrix and I use that matrix to draw it using Heatmap() from complex heatmap! It won't be as beautiful as the original one but at least an option! :D 
Thank you so much again!

**Comment by MayaCyTOFnewbie** [comment]
Hi! 

I'm trying for days now to edit the legend font size without success (crying face) 

I see this post is from two years ago, is there an easier solution today?

many thanks!
Maya

**Comment by HelenaLC** [comment]
Unfortunately not... this is not `CATALYST`-related, but about the `ComplexHeatmap` package. Unlike `ggplot2`, there's no option to, e.g., set a base font size via `... + theme_x(base_size = 9)` *after* generating the plot. One possible option is to play with `draw` (as mentioned above) and `ht_opt`... I agree this is painful. I went through similar issues trying to modify figures for a paper. In the long run, because I do like the package, might be worth posting an issue to the `ComplexHeatmap` authors.
