### ISSUE TITLE
Spillover matrix dimension

### ISSUE THREAD

**Issue by chuancn** [HelenaLC/CATALYST#221]
First of all thanks a lot for this wonderful package. I am quite new to CATALYST and R itself, and have come across the following issue with the dimension of the spillover matrix when making compensation. I will explain using the example data and code from the package:

```
data(ss_exp)
bc_ms <- c(139, 141:156, 158:176)
sce <- prepData(ss_exp)
sce <- assignPrelim(sce, bc_ms, verbose = FALSE)
sce <- applyCutoffs(estCutoffs(sce))
sce <- computeSpillmat(sce)
sm <- metadata(sce)$spillover_matrix
```
Here "sm" is a matrix of 36x39, while "ss_exp" has 39 channels. I thought we usually should do compensation with a square matrix. So I tried compensation using spillover matrices "sm" and an "sm2" that is part of "sm" but 36x36:

```
ele <- Reduce(intersect, list(colnames(sm),rownames(sm)))
sm2 <- sm[ele,ele]

data(mp_cells)
sce <- prepData(mp_cells)

sce1 <- compCytof(sce, sm, method = "nnls", overwrite = FALSE)
sce2 <- compCytof(sce, sm2, method = "nnls", overwrite = FALSE)
```
The resulting expression levels turned out not to be the same:
```
exp1 <- t(sce1@assays@data@listData$compexprs)
exp2 <- t(sce2@assays@data@listData$compexprs)
identical(exp1, exp2)
```
[1] FALSE
`max(abs(exp1 - exp2))`
[1] 2.892487

which is not trivial. The most different expression values come from the channels not existing in the spillover matrix "sm", in this case, "Gd157Di".  When I check again excluding these channels, the difference is still not that small:
```
expdiff <- exp1 - exp2
max(abs(expdiff[, rownames(sm2)]))
```
[1] 0.12536

Would there be a huge impact on the expression data in this case? Another question is, if I have an experiment with more channels, e.g. 42, would it be fine to use either the 39x36 or 36x36 matrix to do compensation? Any answers or comments will be highly appreciated.

**Comment by HelenaLC** [comment]
Thanks for the encouraging words. I understand how this can be confusing, let me try to clarify step by step:
- Spillover is estimated from "spillers" to "receivers" (e.g., channel X = spiller affects channels Y,Z = receivers).
- For any spiller, there's a fixed set of receivers: +/-1M = sensitivity, +16M = oxidation, same M = isotopes.
- Now, say our panel has channels A-C, but B is empty. Then, we can only estimate spill from A and C, but B could be a receiver. Hence, the resulting spillover matrix could be of dimension 2x3 (A,C x A,B,C). 

Overall, you should always use the complete matrix (39x36), not a square part of it (36x36). Otherwise, spillover into empty channels would not be taken into account. Because compensation uses a (NN)LS approach, all values in the matrix will affect the optimisation! Specifically, we want to minimise real * SM^-1 / CM - observed with a non-negativity constraint (here, SM = spillover matrix, CM = compensation matrix / inverse of SM).

**Comment by chuancn** [comment]
@HelenaLC Thanks for your very detailed answer. A follow-up question is, if I have an experiment with more channels (e.g. 110-116Cd, 194-198Pt), would it still be fine to compensate using the existing 39x36 matrix or I should generate new matrix with beads covering all those channels?

**Comment by HelenaLC** [comment]
"Fine" is difficult to say ;) If you had a read at our paper (https://doi.org/10.1016/j.cels.2018.02.010), it's of course always best to acquire a matrix from a single-stained bead experiment run along with the actual experiment. This is, however, infeasible at times. So one might resort to re-using a SM acquired previously. Ideally, this shouldn't be too old and use the same panel. Again, different panels lead to different interactions that lead to inaccurate compensation. So, overall, it's a trade-off between feasibility and accuracy, and it might be worth doing some quality control checks if you use a non-ideal SM for compensation.

**Comment by chuancn** [comment]
Thanks again Helena, this is great help for me!
