### ISSUE TITLE
filter sce data

### ISSUE THREAD

**Issue by Ivy-ops** [HelenaLC/CATALYST#230]
Hi developer, 

I see filterSCE() function, which can subset the sce object by filtering the metadata. 
1. May I know how to exclude the samples with n_cells < a number. 
`filterSCE(sce, condition == "type", n_cells > 10000)`, but it seems it does not works. 
sce@metadata$experiment_info contains n_cells columns. But my input metadata does not contain this column. 
2. Does CATALYST supports filtering the sce object by the "antigen"? Like subset a part of antigens in the later analysis. 

Thank you!

**Comment by HelenaLC** [comment]
1. It depends on **what** number of cells you want to filter by (which is why this is not straightforward to wrap into `filterSCE`). Do you mean the number of cells in a given sample, cluster, condition, or what? 

E.g., to keep samples with more than `n` cells, you'd use
```
# set threshold
n <- 100 
# get number of cells each sample
s_ids <- sce$sample_id
ns <- table(s_ids)
# get samples to keep
s_keep <- names(ns)[ns > n]
# subset
sub <- filterSCE(sce, sample_id %in% s_keep)
```

To filter clusters:
```
# get cluster IDs to use
k <- "meta10"
k_ids <- cluster_ids(sce, k)
ns <- table(k_ids)
k_keep <- names(ns)[ns > n]
sub <- filterSCE(sce, k = k, cluster_id %in% k_keep)
```

To filter cluster-sample combinations (this is a little more tricky...):
```
ns <- table(
    sample_id = sce$sample_id, 
    cluster_id = k_ids)
ns <- as.data.frame(ns)
ks_keep <- ns$Freq > n
ns <- ns[ks_keep, ]

sub <- filterSCE(sce, k = k,
    sample_id %in% ns$sample_id & 
    cluster_id %in% ns$cluster_id)
```

2. Yes, absolutely. This isn't really filtering, but just simple subsetting. In the `SingleCellExperiment`(SCE) rows = features, columns = observations. So you can subset the antigen(s) of interest via `sce[i, ]`, where `i` are the features you want to keep, e.g., `i = c("CD4", "CD8", "XYZ", ...)`
