### ISSUE TITLE
Shiny app, adjustment of the cofactor in compensation/before vs after scatters

### ISSUE THREAD

**Issue by schevrie** [HelenaLC/CATALYST#25]
In the shiny app, in compensation, before vs after scatter, it is possible to incrementally change the cofactor by clicking on the small arrow next to the number. 
however, if we use the arrow to go from 5 to 20 for instance, the graph will then be refreshed 15 times. I think having those arrows are not useful and I would only leave the option to enter the number, which is the most efficient button since once we hit enter, the graph gets updated straightaway and we don't have to think ok now on which button should I click if I want to validate my choice :).

**Comment by HelenaLC** [comment]
The "numericInput" widget of Shiny has these arrows by default and I cannot remove them. I changed the "step" from 1 to 5, so that at least the cofactor will adjust considerably when the arrows are clicked. Alternatively, it could be a select input with options 2, 5, 10, 20, 50, 100 for example. Thoughts?
