### ISSUE TITLE
recluster  

### ISSUE THREAD

**Issue by MayaCyTOFnewbie** [HelenaLC/CATALYST#266]
Hi there,

I ran flowSOM clustering using a narrow panel selection as type, so I got the major populations.

now, I want to select a specific population e.g. CD4 T cells, and use a different set of markers as type markers. is there a was to edit the panel within an SCE object? or would it be easier to export fcs files for the specific cluster of interest, and create a new SCE object?

Thanks!

Maya

**Comment by HelenaLC** [comment]
`prepSCE()` is just to initialise the object from a set of FCS files, panel and metadata table. But you can of course modify its data at any point. Something like this should do the trick:
```
data(PBMC_fs, PBMC_panel, PBMC_md)
sce <- prepData(PBMC_fs, PBMC_panel, PBMC_md)
sce <- cluster(sce, verbose = FALSE)

# subset some subpopulation 
sub <- filterSCE(sce, cluster_id %in% c(...))

# redefine type markers
use <- c(...)
not <- setdiff(rownames(sub), use)
rowData(sub)[use, "marker_class"] <- "type"
rowData(sub)[not, "marker_class"] <- "state"

# recluster
sub <- cluster(sub, verbose = FALSE)
```

**Comment by ramziabb** [comment]
I started working with sub clustering today.  Thank you for the code sample.

I had to make a couple of adjustments to get it to work, wanted to see if they looked right to you.

`
# Subset out just the T cells
sub <- filterSCE(sce, cluster_id %in% c(7,9,10), **k=strClusters**)  # without adding k=strClusters, where strClusters is metaXX, has to be the same as the original clustering, it doesn't pick out the right clusters.
plotExprHeatmap(sub, features = "type", by = "cluster_id", k = strClusters) # shows just the clusters and type markers you selected above.

# redefine type markers
state <- rownames(sub)[c(3,6,15)] # need to get the rownames, not just the row numbers.
type <- setdiff(rownames(sub), state)
rowData(sub)[type, "marker_class"] <- "type"
rowData(sub)[state, "marker_class"] <- "state"

# recluster
numClusters <- 20         # The new number of clusters.
strClusters <- "meta20"   # The new number of clusters.
sub <- cluster(sub, features = "type", xdim = 10, ydim = 10, maxK = numClusters, seed = randSeed)

# Figure 6: Heatmap of median marker intensities - of your subclustering.
plotExprHeatmap(sub, features = "type", by = "cluster_id", k = strClusters, row_anno = TRUE, bars = TRUE, perc = TRUE, bin_anno = FALSE)

**Comment by ramziabb** [comment]
After doing filterSCE and then changing the "type" and "state" designations, the column labeled used_for_clustering (boolean) remains set up for the original type/state designations.  Does that column need to be changed as well for the second clustering call?  Or does it automatically change this over in the code based on the value of "marker_class"?
```

> rowData(sceSubCluster)
DataFrame with 15 rows and 4 columns
           channel_name marker_name marker_class **used_for_clustering**
            <character> <character>     <factor>           <logical>
CD45RA  CD45RA-BUV395-A      CD45RA        type                FALSE
CD8        CD8-BUV496-A         CD8        type                FALSE
CD56      CD56-BUV737-A        CD56        state                TRUE
CD197     CD197-BV421-A       CD197        type                FALSE
CCR5     CCR5-PacBlue-A        CCR5        type                FALSE
...                 ...         ...          ...                 ...
CD183        CD183-PE-A       CD183        type                FALSE
CCR4     CCR4-PECF594-A        CCR4        type                FALSE
CXCR5     CXCR5-PECY7-A       CXCR5        type                FALSE
CCR10       CCR10-APC-A       CCR10        type                FALSE
CD14   CD14-APCVIO770-A        CD14        state                TRUE
```

**Comment by ramziabb** [comment]
Has anyone tried to implement this?  I am getting some results I am concerned are incorrect.

1. Sample 1: cluster my data into 50 clusters, then merge them down to defined clusters.
![image](https://user-images.githubusercontent.com/93796927/162060736-4b724192-09b8-4d99-8092-bc90bec27a9b.png)

2. Sample 2: cluster my data into 10 clusters, pick two of them, cluster those into 20 clusters, then merge them down to defined clusters.
![image](https://user-images.githubusercontent.com/93796927/162060634-83a292a0-0c39-49bf-9a40-59784e6b7b32.png)

The expression levels are completely different.  I circles Tregs, a population that is extremely cut and dried, I would imagine the cells chosen in either clustering algorithm should be virtually the same.  But the result, meaning the number of Tregs found in the three control samples are completely different, and in fact inverted.

Is this simply a loss of power?  It seems very strange to me, that something would go from hot to cold this way.

Going back to find a root cause, I looked at heatmaps from my original 10 clusters:
![image](https://user-images.githubusercontent.com/93796927/162061096-bfca0f01-4128-4c56-b73f-20b58b4155e1.png)

I then subset out just the CD3+ t-cells, clusters 1 and 4:
`# Subset out just the T cells
sceSubCluster <- filterSCE(sce, cluster_id %in% c(1,4), k=strClusters)
plotExprHeatmap(sceSubCluster, features = "type", by = "cluster_id", k = strClusters)
`

Look at how the relative "median scaled expression" of CD3 and CD56 expression changes when the heatmap is replotted.  Maybe this isn't a problem - if "median scaled expression" is individually determined for each column, and has no relationship to the other columns.  But still interesting.  The Cd3 went from around 1 in both original clusters to closer to 0.7 (ish) in the second plot, and the cluster 4 CD56 went out to each extreme (high and low) :
![image](https://user-images.githubusercontent.com/93796927/162061304-afcbd076-f0f4-431e-bace-5e3ce6bca88b.png)

I am concerned some expression / MFI data is getting lost or overwritten.  But maybe everything is working correctly and these difference are attributable solely to the clustering sorting the cells differently and changes in sample sizes.  

Few follow up questions that come to mind:
1. Can you provide a line of code to display the number of cells in a cluster?  I know it can be displayed in the heat maps, but I want to see how big these clusters are using different methodologies.  
2.  Is there code to write out FCS files from the clusters?  Could I for instance write out the flow data into FCS files entitled "Cluster 1.fcs", "Cluster 2.fcs" with the original data form each cell, just sorted into FCS files by cluster.  Maybe adding a column to specify which sample that cell came from?  This would allow me to confirm the statistical results.

Bunch of different questions in here.  I can separate them into multiple issues if necessary.  

**Being able to subcluster would save me (and others) a lot of time and also allow us to find rare populations.  But I wonder if I have made a mistake somewhere in my methodology.**

To be complete, this my adaptation of your code to do the comparison analysis:
` sub <- filterSCE(sceSubCluster, condition %in% c("Control", "Itacitinib"))

ei <- metadata(sceSubCluster)$experiment_info
ei <- ei[ei$condition == "Itacitinib" | ei$condition == "Control", ]

contrast <- createContrast(c(0, 1))

(da_formula1 <- createFormula(ei, 
                              cols_fixed = "condition", 
                              cols_random = "patient_id"))

da_res1 <- diffcyt(sub, 
                   formula = da_formula1, contrast = contrast,
                   analysis_type = "DA", method_DA = "diffcyt-DA-GLMM",
                   clustering_to_use = "merging1", verbose = FALSE)

names(da_res1)

rowData(da_res1$res) 
table(rowData(da_res1$res)$p_adj)
table(rowData(da_res1$res)$p_adj < FDR_cutoff)

myPlot <- NULL
myPlot <- tryCatch( {
  hm <- plotDiffHeatmap(sub, rowData(da_res1$res), all = TRUE, fdr = FDR_cutoff)
  funColorConditions2(hm)
  hm
}, error=function(e) {
  message("Error in Plot 22.1")
  message(e)
  return(NULL)
})
myPlot

if (!is.null(myPlot)) {
  funWritePlotPDF("Plot 22.1. Compare Each Cluster Itacitinib vs. Control.PDF")
} `


Thank you,
Ramzi

**Comment by HelenaLC** [comment]
1. To display the number of cells by cluster, you can use `table(cluster_ids(sce, k = "clusteringID"))`. For cells by sample-cluster, `table(cluster_ids(sce, k = ...), sce$sample_id)` (or `sce$condition` for by condition-cluster etc.)
2. To write out FCS files of different subsets (e.g., by cluster, sample etc.), please see [here](https://bioconductor.org/packages/release/bioc/vignettes/CATALYST/inst/doc/differential.html#exporting-fcs-files) (generally, always worth checking the vignette before getting stuck / posting an issue :)

**Comment by HelenaLC** [comment]
Regarding the heatmaps: Something worth playing with is the `scale` argument in `plotExprHeatmap`: 
```
character string specifying the scaling strategy:
  "first": scale & trim then aggregate
  "last": aggregate then scale & trim
  "never": aggregate only
If scale != "never", data will be scaled using lower (q%) and upper (1-q%) quantiles as boundaries.
```
This can have quite a dramatic effect on the visualisation! Each serves a different purpose, so it depends on what one is interested in. E.g., not scaling will keep the relative difference between lowly/highly expressed markers, but differences might vanish if, say, one marker rules them all. On the other hand, scaling last will have all markers appear high somewhere.

**Comment by HelenaLC** [comment]
Regarding the discrepancy between the 2 DA results above, I cannot be sure what exactly is happening as the clustering procedure is so different. My rough thoughts are
- in (1) you start with 50 clusters, merge, and get 1 cluster with 2/3 samples in the control having more Tregs, but in the plots above I cannot see how big that cluster is.
- in (2) you start with 10, subset 2, recluster into 20. Perhaps the initial clustering already does not get the same cluster(s) as in (2) if Tregs are small? 
- generally, I'd highly encourage more intermediate, exploratory visualisation. E.g., simply the number of cell by cluster / sample-cluster / condition-cluster (`plotCounts`) as well as their relative abundances stratified in different ways (`plotAbundances`). DA analysis and the corresponding `plotDiffHeatmap` visualisations should come last, and be interpreted / supplemented by the former.

**Comment by ramziabb** [comment]
> 1. To display the number of cells by cluster, you can use `table(cluster_ids(sce, k = "clusteringID"))`. For cells by sample-cluster, `table(cluster_ids(sce, k = ...), sce$sample_id)` (or `sce$condition` for by condition-cluster etc.)
> 2. To write out FCS files of different subsets (e.g., by cluster, sample etc.), please see [here](https://bioconductor.org/packages/release/bioc/vignettes/CATALYST/inst/doc/differential.html#exporting-fcs-files) 

Very useful.  I have started interrogating the data to see where the differences are.

**Comment by ramziabb** [comment]
> Regarding the heatmaps: Something worth playing with is the `scale` argument in `plotExprHeatmap`:
> 
> ```
> character string specifying the scaling strategy:
>   "first": scale & trim then aggregate
>   "last": aggregate then scale & trim
>   "never": aggregate only
> If scale != "never", data will be scaled using lower (q%) and upper (1-q%) quantiles as boundaries.
> ```
> 
> This can have quite a dramatic effect on the visualisation! Each serves a different purpose, so it depends on what one is interested in. E.g., not scaling will keep the relative difference between lowly/highly expressed markers, but differences might vanish if, say, one marker rules them all. On the other hand, scaling last will have all markers appear high somewhere.

The scaling wouldn't change the underlying values though, correct?  It is just for the coloring of the heatmaps.

**Comment by HelenaLC** [comment]
Well, yes, if I understand correctly. The "underlying values" will be unaffected meaning that the `sce` object will not change. It is just visualised. So the values extracted via, e.g., `hm <- plotExprHeatmap(); hm@matrix` will be different as the data is scaled internally. But the `sce` isn't affected as we don't overwrite it (`sce <- ...`) anywhere.
