### ISSUE TITLE
Order UMAP based on expression

### ISSUE THREAD

**Issue by bioguy2018** [HelenaLC/CATALYST#270]
Dear Helena,
I am wondering is there an option to sort the UMAP layouts in a way that the highest expression be on top ? I sometimes have came to the problem that the cells with high expressions are buried inside. Is there a solution to avoid that?

Thank you so much

**Comment by HelenaLC** [comment]
Hi, So... I would generally not recommend doing this. I'd argue that ordering points/cells according to their expression can be misleading: E.g., say 1% of cells have an extremely high expression and cover 99% of lowly expressing cells. Of course, this is an extreme example that is just meant for illustration.
Instead, what is "typically" done (from what I've seen) is to randomly shuffle cells in order to avoid visual artefacts: 

```r
# shuffle cells globally
sce <- sce[, sample(ncol(sce))]
```

Similarly, one might consider to downsample a subset of cells per, say, sample/patient etc. to avoid one ruling them all. This is done, for example, in accordance with the `n_cells` argument in `runDR`, which will perform dimensionality reduction on a random subset of cells per `sample_id`. But if one were interested in downsample by another variable (for visualisation), they'd do something like:

```r
n <- 100 # maximum number of cells to keep
idx <- split(seq(ncol(sce)), sce$variable)
idx <- lapply(idx, \(.) sample(., min(n, length(.)))
sub <- sce[, unlist(idx)]
```
