### ISSUE TITLE
scater runDiffusionMap deprecated

### ISSUE THREAD

**Issue by TarikExner** [HelenaLC/CATALYST#283]
Dear CATALYST-maintainers,

thank you very much for this helpful package!

Using CATALYST version 1.20.0 and scater version 1.24.0, the runDR(x, dr = "DiffusionMap", features = NULL) throws a Defunct error.

Apparently, scaters runDiffusionMap-function is deprecated. UMAP, PCA and TSNE work fine.

The following workaround did the trick for us:
'''
remove.packages("scater")
devtools::install_github("alanocallaghan/scater@RELEASE_3_12")
BiocManager::install("destiny")
'''
where all functionality is restored. Release 3_12 corresponds to 1.18.1. Scater 1.20.1 also works on a labmate's computer.

Can you think of a solution for this?

Thank you very much.

**Comment by HelenaLC** [comment]
Hm. Maybe I'm missing something, but I don't really see the issue here - I also got this when trying to run `runDR(..., dr = "DiffusionMap")`
```
Error in loadNamespace(x) : there is no package called ‘destiny’
In addition: Warning messages:
1: 'fun' is deprecated.
See help("Deprecated") 
2: 'calculateDiffusionMap' is deprecated.
See help("Deprecated") 
```
However, this is just telling me "you need to install `destiny` because it's not a `scater` dependencies / not key functionality", which is fine. When I install destiny via `BiocManager::install("destiny")`, it runs with the following warnings:
```
Warning messages:
1: 'fun' is deprecated.
See help("Deprecated") 
2: 'calculateDiffusionMap' is deprecated.
See help("Deprecated") 
```
but the output SCE contains the dimension reduction as it should. Again, this is fine for me because it just says "some maintainers have deprecated some functions that others are still using and they should eventually update this". If they do not, and these functions are removed eventually (which is how deprecation works; give a warning, wait for a release cycle, remove), the method would indeed fail - then, and only then, `scater` would probably remove this option completely, unless there's an alternative to compute the diffusion map.

**Comment by TarikExner** [comment]
Thank you for the fast reply!


When we run runDR(x, dr = "DiffusionMap", features = NULL), the script crashes. The exact error message is:

`Error: 'fun' is defunct.
See help("Defunct")`

if we then run:
`library(destiny);
runDR(x, dr = "DiffusionMap", features = NULL)`

the script still crashes and the error message is unchanged:
`Error: 'fun' is defunct.
See help("Defunct")`

I attached the sessionInfo() output.

I will do some more digging and keep you updated. 



`> sessionInfo()
R version 4.2.0 (2022-04-22 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22000)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.utf8  LC_CTYPE=German_Germany.utf8   
[3] LC_MONETARY=German_Germany.utf8 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.utf8    

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] destiny_3.10.0              PeacoQC_1.6.0              
 [3] flowAI_1.26.0               ggplotify_0.1.0            
 [5] viridis_0.6.2               viridisLite_0.4.0          
 [7] ggpubr_0.4.0                ggrastr_1.0.1              
 [9] ggplot2_3.3.6               dplyr_1.0.9                
[11] RColorBrewer_1.1-3          pheatmap_1.0.12            
[13] flowCore_2.8.0              CATALYST_1.20.1            
[15] SingleCellExperiment_1.18.0 SummarizedExperiment_1.26.1
[17] Biobase_2.56.0              GenomicRanges_1.48.0       
[19] GenomeInfoDb_1.32.2         IRanges_2.30.0             
[21] S4Vectors_0.34.0            BiocGenerics_0.42.0        
[23] MatrixGenerics_1.8.0        matrixStats_0.62.0         
[25] BiocManager_1.30.18 `

**Comment by HelenaLC** [comment]
According to `?scater::defunct`, `runDiffusionMap` has "passed on to the function afterlife", and has "no replacement. `destiny` is no longer on Bioconductor. You can calculate a diffusion map yourself, and add it to a `reducedDim` field, if you so wish." The `dr = "DiffusionMap"` option will be removed from `runDR` with the next push.
