### ISSUE TITLE
define cofactor in prepdata for each antigen

### ISSUE THREAD

**Issue by RebeccaPPayne** [HelenaLC/CATALYST#286]
I have been using Catalyst and the CYTOF workflow published by your teams in F1000 for a while now on our Cytof data, we love it and have found it really great and flexible for our work especially with novice R users. So firstly, thank you so much for this great contribution!
We are switching our technologies and have recently optimised a panel on spectral flow Aurora and wanted to use the pipeline for this work also but we are finding the cofactor of 5 in prepdata doesnt work too well for the different flourescent antibodies (especially tetramers) and wondered if there was a way to define different cofactors for each antigen in this step?

thanks
Becky

**Comment by HelenaLC** [comment]
Dear Rebecca,
Yes, there is a way! If you have a look at `prepData()`'s documentation of the `cofactor` argument (see `?prepData`), it states that:

*"numeric cofactor(s) to use for optional arcsinh-transformation when `transform = TRUE`; single value or a vector with channels as names."*

In other words: You can use channel-specific cofactors by providing `cofactor` with a vector of the form `c("Ab123" = 5, "Cd456" = 10, ...)`. 

Let me know if this works out or you run into issues / have further questions. Otherwise, close the issue if all goes well; thanks :)!!

**Comment by SamGG** [comment]
Great addition. I missed that point. Thanks Helena!
