### ISSUE TITLE
Using CATALYST without sample barcodes

### ISSUE THREAD

**Issue by suginoka** [HelenaLC/CATALYST#293]
Hi CATALYST team,

I have some CyTOF sample data I’m trying to process, but I’ve run into an issue when trying to follow the CATALYST tutorial using my samples. My samples were run without barcodes so I have individual fcs files for each sample, which I read into R using list.files() and prepData() commands. I was able to get through the normalization step, but the compensation step uses the output from the debarcoding step, so I am unable to run my sce through the computeSpillmat() command since I do not have barcodes to run the previous debarcoding protocol.

Do you know of a workaround for this? I’ve looked through the example dataset and tutorial outputs and the only thing I can think to do to match my files to the tutorial file format is to create dummy channels in each of my sample files and then create a sample_key that can be run through the debarcoding steps. I’m not great with R, so I have no idea how to do this and would like to avoid directly editing my fcs files if possible. I also already know which events belong to which samples, so there could be some way to utilize this information within the program or data structure I’m just not sure how.

Thank you!
Kameron

**Comment by HelenaLC** [comment]
Hm, I believe there might be a misunderstanding here regarding the general experimental/computational workflow:
- The compensation relies on single-stained beads. These (not the samples) go through debarcoding (using a "dummy" scheme with all 0s and one 1 for the every bead mass) in order to identify events from each channel. These are in turn used to estimate spillover, compute the compensation matrix, and compensate the measurement data. 
- So, the sample(s) themselves don't require debarcoding in order to be compensated. Nevertheless, you'd of course want to do this to know where the samples' cells came from. In the end, all that debarcoding would do (in its essence) would be to add a `bc_id` column to the SCE's `colData` according to the debarcoding scheme. Since you don't have this, I'd suggest a workaround such as the following:
```
# get FCS file names
fcs <- list.files(...)    
# read in as 'flowSet'
fs <- read.flowSet(...)
# get number of events in each sample
ns <- fsApply(fs, nrow)
# construct SCE
sce <- prepData(fs, ...)
# assign sample IDs
sids <- paste0("sample", seq(length(fs)))
sce$bc_id <- rep.int(sids, ns)
```
