### ISSUE TITLE
Question about prepData with transform = FALSE

### ISSUE THREAD

**Issue by purisuto** [HelenaLC/CATALYST#296]
Hi there,

Lately I'm prepping sce of CyTOF data with `transform = FALSE`. This data was already arcsin 5 transformed because I sent it through the fantastic cyCombine batch correction workflow.  Thus in `compCytof()`, It seems that I also have to set `transform = TRUE, cofactor = 5`.  I was wondering if this is correct?

Also, in `prepData()` when I forgot to set `transform = FALSE`, this presumably arcsin 5 transformed already transformed data. However I noticed that it didn't seem to give different results in the CATALYST workflow (heatmaps were identical).  Any information you could provide would be greatly appreciated.

Kind Regards,
David Priest

**Comment by HelenaLC** [comment]
Hm, if I understand correctly, this is a little tricky. Here a couple thoughts:
- If you have a look at the `computeSpillmat()` and `compCytof()` documentation, compensation relies on linearity assumptions, i.e., the input is expected to be count-like data for both.
- For `compCytof()`, when `transfrom = TRUE`, transformation will be applied to the compensated counts. That is, input data is left as-is, compensated, and then transformed and written to another assay slot (or the same, if `overwrite = TRUE`).
- So, taken together, my best guess is that you want to set `transform = FALSE` in `prepData()`, and manually back-transfrom the data (given the previously applied cofactor) in order to obtain data on the count-scale. These should then be used as input for `computeSpillmat()` (beads) and `compCytof()` (cells). For the latter, again, `transfrom = TRUE` will simply transform the compensated data to an expression-like scale, which could also be done manually downstream and does not affect compensation.

Regarding your other point that this "didn't seem to give different results" I am not sure, and would have to see more of the data. E.g., there's a difference between the data really being the same (shouldn't be the case I hope) and just looking the same in the heatmaps. Specifically, with default parameters, heatmaps apply a 0-1 rescaling of the data that might make it appear identical, though the original scales are different. Perhaps worth checking something like `rowRanges(assay(sce))` on the SCE resulting from `prepData()` with `transform=TRUE/FALSE`?

**Comment by purisuto** [comment]
Thank you very much!  Indeed I have been running `compCytof()` on data that was arsinh 5 transformed (either in cyCombine or `prepData`)!  Could you please direct me to the function for transforming/back-transforming an sce?

**Comment by HelenaLC** [comment]
`CATALYST` uses an internal helper function to do this, which can be accessed via `CATALYST:::.transform()`; also posting it here for completeness:
```
# x = SingleCellExperiment
# cf = numeric cofactor
# ain = input assay name
# aout = output assay name
# dir = transformation direction
.transform <- function(x, cf, 
    ain = "counts", aout = "exprs", 
    dir = c("forwards", "backwards")) {
    dir <- match.arg(dir)
    chs <- channels(x)
    stopifnot(is.numeric(cf), cf > 0)
    if (length(cf) == 1) {
        int_metadata(x)$cofactor <- cf
        cf <- rep(cf, nrow(x))
    }
    else {
        stopifnot(!is.null(names(cf)), chs %in% names(cf))
        cf <- cf[match(chs, names(cf))]
        int_metadata(x)$cofactor <- cf
    }
    if (dir == "forwards") {
        fun <- asinh
        op <- "/"
    }
    else {
        fun <- sinh
        op <- "*"
    }
    y <- assay(x, ain)
    y <- fun(sweep(y, 1, cf, op))
    assay(x, aout, FALSE) <- y
    return(x)
}
```

**Comment by purisuto** [comment]
Perfect! Thank you very much.
