### ISSUE TITLE
Reading in Ctytoff data with Prepdata in CATALYST package

### ISSUE THREAD

**Issue by Ind2022** [HelenaLC/CATALYST#297]
Hello Dr.Crowell,

Currently I am working with some Cytoff data and initially preprocessing & Clustering with “imcRTools” package.
This package results in “spatial experiment class object” with cluster ids added to spatial class object. And for further downstream analysis and plotting , I am interested to use CATALYST package as it has many good built in-functions. Mainly functions like:plotClusterHeatmap, plotClusterExprs, runDR, mergeclusters etc.
 
If possible, it will be very helpful, if could you please suggest, how to read in a spatial experiment class object including clusters assigned by imcRTools with prepData function.

Thank you so much for this wonderful package.

**Comment by HelenaLC** [comment]
Hi there. Thanks for the inquiry and interest! I definitely think many of the visualizations are applicable to other data types, and we have ourselves used `CATALYST` for both scRNA-seq and CITE-seq data. Here's how I'd do this:
- The fact that you're having a `SpatialExperiment` (SPE) already makes things a lot easier. Since the SPE class inherits from the 'SingleCellExperiment' class, `CATALYST`'s S4 method dispatching would allow all functions to already work, in principle.
- However, there are are feature (`rowData`), sample (`colData`) and experiment-wide metadata (`metadata`) that are expected to exist by `CATALYST`. By default, these would be something 
  -`rowData`: at least a `marker_class` column (type/state/none) that'll determine which features to plot/use for dimensionality reduction etc.
  - `colData`: at least a `sample_id` (unique identifier), `condition` (experimental group) and `cluster_id` (cell subpopulation assignment) column
  - `metadata` (perhaps the most tricky): at least a `cluster_codes` element to match cells to `cluster_id`s

Here's a minimal reproducible example how to get a random SPE into a `CATALYST`-compatible structure. Let me know how it goes or if you have any further issues/questions; happy to help and get this working as it might also me useful for other users.
```
library(CATALYST)
library(scuttle)
library(STexampleData)

# get some exemplary 'SpatialExperiment'
spe <- Visium_humanDLPFC()

# expression-values should be 
# in an assay named 'exprs
spe <- logNormCounts(spe, name = "exprs")
# of type matrix (not sparse)
assays(spe)[[2]] <- as.matrix(assays(spe)[[2]])

# set up feature metadata
gs <- rownames(spe)
rd <- data.frame(
    row.names = gs,
    marker_class = factor(
        rep("none", nrow(spe)), 
        c("type", "state", "none")))
# sampling some random genes as type/state
rd[type <- sample(gs, 10), "marker_class"] <- "type"
rd[sample(setdiff(gs, type), 10), "marker_class"] <- "state"
rowData(spe) <- rd

# set up sample metadata
spe$condition <- factor(spe$in_tissue)
spe$cluster_id <- factor(spe$ground_truth)

# construct cluster codes table
df <- data.frame(meta20 = spe$cluster_id)
metadata(spe) <- list(cluster_codes = df)

# this should work now
spe <- runDR(spe)
plotDR(spe, color_by = "cluster_id")
```

**Comment by Ind2022** [comment]
Hello Dr.Crowell,

Thank you so much for your suggestions. It worked with spatial object. I will be proceeding with merging clusters as well as differential analysis. And reply back here in case I need your suggestion again. 

Your package will be very helpful in downstream analysis.

**Comment by HelenaLC** [comment]
Great, glad to hear it’s running (for now)! Feel free to reopen in case any issues/questions arise downstream. Cool to hear the package/visualizations is/are proving useful across techs!
