### ISSUE TITLE
File size issues

### ISSUE THREAD

**Issue by vkwoodco** [HelenaLC/CATALYST#43]
Hi

I am trying to use the CATALYST Shiny app for compensation and debarcoding of a large sample and am running into problems due to the size of the file.  I have normalised and concatenated using Fluidigm software and the resultant fcs file is around 12GB.  When I try and load this into the 'upload multiplexed data' section in the ShinyApp compensation tab I get an error 'Maximum upload size exceeded'.  

I have also tried loading the individual normalised files in and concatenating within CATALYST and whilst this works, I cannot directly transfer these into the compensation tab without going through normalisation and am unable to download the files as I encounter an error that shows up in the terminal as 'Warning: Error in writeBin: only 2^31-1 bytes can be written in a single writeBin() call'.  

Is there a way of overcoming the file size limitations? 

Many thanks

**Comment by SamGG** [comment]
Hi
I am not a developer nor a regular user.
For the 1st question, shiny applications are web based, ie the data are transferred from your computer via your web browser to the service (which is also on your computer) as if the application is on the internet. This overhead is time and disk space consuming. Try to find the R commands that will carry out the process you want, especially because your file is very large.
The 2nd problem looks like a problem of flowCore. Please post this issue on  https://github.com/RGLab/flowCore
Hope this help.
