### ISSUE TITLE
Preventing arcsinh transformation

### ISSUE THREAD

**Issue by bioguy2018** [HelenaLC/CATALYST#56]
Dear developers,
I have a preproccesed facs files which is already transformed and I do not wish to transform it again when I run daFrame() function. Is this an option ? I couldn't find it on the documentation although it was mentioned I can have my own transformation.

Thanks a lot

**Comment by HelenaLC** [comment]
I am working on a major revision of `CATALYST` for Bioc 3.10, which will be released in October I believe. This will - among a thousand other things - include skipping the transformation step!

As a temporary fix, you can replace the `daFrame`'s expression matrix with whatever you like (`daf@assays$data$exprs <- ...`), provided you're confident in what you're doing, e.g., make sure dimension names etc. are correct ;) 
This is of course not ideal and really bad habit coding, and I apologize, but I'm confident many things will significantly  improve in October!

**Comment by bioguy2018** [comment]
Dear @HelenaLC ,
I am wondering is using another transformation method or skipping the arcsin transformation has been already implemented in the new version because I couldn't find anything about that in the new API

**Comment by HelenaLC** [comment]
With the new R 4.0.0 and Bioc 3.11 release coming up, there will be significant changes to the package's structure. Mainly, the entire preprocessing pipeline will be using the `SingleCellExperiment` (SCE) class, and with that all functions will be subject to change.

I apologies this is still not in the official release. In the new update, there will be a hopefully more elegant and straight-forward solution, specifically:

* ALL intermediate assays will be stored in the SCE which was not possible with the previous data structure (`dbFrame` class), or other cytometry data structures (e.g., `flowFrame`s).
* This means, for example, after a classical preprocessing workflow, the SCE could contain assays `counts`, `exprs`, `normed`, `comped`, `scaled`.  
* In principle, any transformation can be added by the user. In the 1st step, the default will be returning assays `counts` AND `exprs`, and `transform = NULL` (for no transformation) would return only assay `counts`. 
* Each step will then add additional assays, e.g., `normCytof` gives `normed`, `compCytof` gives `comped` etc.

I hope this will make things a lot easier! Especially since each data is not overwritten but kept in a single object. Thanks for your patience and working around this until then!

**Comment by SamGG** [comment]
Great job!!! I'll wait for this nice integration.
Thanks.
