### ISSUE TITLE
Problem with plotExprHeatmap

### ISSUE THREAD

**Issue by algebio** [HelenaLC/CATALYST#63]
Hi 

I´m trying to produce a heatmap from some suspension cytof files. When I use plotExprHeatmap(daf, bin_anno = TRUE, row_anno = TRUE) I get this error message:

Error in hclust(get_dist(t(submat), distance), method = method) : NA/NaN/Inf in foreign function call (arg 11)

Traceback:

16.
hclust(get_dist(t(submat), distance), method = method)
15.
make_cluster(object, "column")
14.
.local(object, ...)
13.
make_column_cluster(object)
12.
make_column_cluster(object)
11.
.local(object, ...)
10.
prepare(object@ht_list[[i]], process_rows = FALSE)
9.
prepare(object@ht_list[[i]], process_rows = FALSE)
8.
.local(object, ...)
7.
make_layout(object, row_title = row_title, row_title_side = row_title_side, row_title_gp = row_title_gp, column_title = column_title, column_title_side = column_title_side, column_title_gp = column_title_gp, heatmap_legend_side = heatmap_legend_side, merge_legends = merge_legends, ...
6.
make_layout(object, row_title = row_title, row_title_side = row_title_side, row_title_gp = row_title_gp, column_title = column_title, column_title_side = column_title_side, column_title_gp = column_title_gp, heatmap_legend_side = heatmap_legend_side, merge_legends = merge_legends, ...
5.
.local(object, ...)
4.
draw(object)
3.
draw(object)
2.
(new("standardGeneric", .Data = function (object) standardGeneric("show"), generic = structure("show", package = "methods"), package = "methods", group = list(), valueClass = character(0), signature = structure("object", simpleOnly = TRUE), default = new("derivedDefaultMethod", ...
1.
(new("standardGeneric", .Data = function (object) standardGeneric("show"), generic = structure("show", package = "methods"), package = "methods", group = list(), valueClass = character(0), signature = structure("object", simpleOnly = TRUE), default = new("derivedDefaultMethod", ...

Two weird things:
The weird thing 1 is that when I use the same files together with some imc files, I can get the heatmap fine.
The weird thing 2 is that I can produce the heatmap if I add scale = FALSE.
plotExprHeatmap(daf, bin_anno = TRUE, row_anno = TRUE, scale = F)

Any idea of where the problem with those files is?

Regards
Juan

**Comment by HelenaLC** [comment]
Could you share a screenshot of the heatmap with scale=F? Given the scaling is causing the issue, it’d be helpful to have an idea what the issue looks like.

**Comment by markrobinsonuzh** [comment]
I think I had a similar problem once when the variance=0 for one of the channels (markers). Scaling has a problem with that.

@algebio if you can, perhaps you can share the object you used (privately, if you want) and then we could have a reproducible example.

**Comment by algebio** [comment]
Hi Helena and Mark
I have attached the heatmap. I'll share the object privately.
Thank you for your help.
Regards
Juan

![heatmap](https://user-images.githubusercontent.com/40662428/66725020-e03f7800-ee24-11e9-8b7c-258ea96b43b9.png)

**Comment by HelenaLC** [comment]
Thanks, that helped a bunch! The error was caused by both the 1% and 99% quantiles being 0 for one gene, causing the scaled means to be NA. Before, only values < 0 where set to 0, and values > 1 to 1. Now, NA values are set to 0 as well & the error is resolved.

FYI: You can get the fixed version ASAP via `devtools::install_github("HelenaLC/CATALYST", ref = "RELEASE_3_9")`, or wait a couple days for the changes to go on Bioc, then install in the usual way with `BiocManager::install("CATALYST")`.

PS: Just a heads up that the new Bioc release (3.9 to 3.10) will be end of this month; with that, there will be major changes to `CATALYST`. First and foremost, the `daFrame` class will be replaced by a "classical" `SingleCellExperiment`, switching the object dimensions (then, rows = markers, column = cells). Besides, all currently available functions will still exist!

**Comment by algebio** [comment]
Thank you Helena for the great help and all that information.

Regards
Juan
