### ISSUE TITLE
Errors with concatFCS (flowSet)

### ISSUE THREAD

**Issue by Biomiha** [HelenaLC/CATALYST#76]
Hi Helena,

First of all thank you for making the CATALYST package available to the community. I just wanted to let you know I get the following error when running `concatFCS(raw_data, file_num = TRUE, by_time = FALSE)`

Error in eval(quote(list(...)), env) : object 'o' not found

Also, if I try to concatenate the following flowSet:

    data(PBMC_fs)
    tmp <- PBMC_fs[c(1,3)]
    concatFCS(tmp)

I get:
Error in .local(x, ...) : (list) object cannot be coerced to type 'double'

Whereas:

    cydar::poolCells(ncdfFlowSet(tmp), equalize = FALSE)

works.
Something to tweak in the next version perhaps?

Thanks.

**Comment by HelenaLC** [comment]
Fixed with the next release- this includes a major switch from `flowX` data classes to Bioc's `SingleCellExperiment` (SCE) class. `concatFCS` will be replaced by a general FCS/`flowFrame/Set` conversion function, `prepData`, to construct the SCE and concatenate all samples in the process; fixing of event times and sample reordering will also be taken care of by this.
