### ISSUE TITLE
[REQ] R Phenograph as clustering method

### ISSUE THREAD

**Issue by grhogg** [HelenaLC/CATALYST#81]
Hello, 

I was wondering if there was a way to integrate RPhenograph clustering into the CATALYST pipeline as a new feature. If that is quite difficult, I was hoping you could make a suggestion on how to coerce the cluster.id FCS metadata generated from rPhenograph or Phenograph within cytofkit into the CATALYST object for downstream differential analysis and visualization. Thanks!

**Comment by HelenaLC** [comment]
Thanks for the suggestion! In fact, I've already done this in another project. The issue with integrating it as a feature is that a lot of the current "beauty" for CATALYST lies in being able to explore & analyse a range of clustering resolutions. Currently, this is done by matching IDs from the `metadata(sce)$cluster_codes` table, which in turn requires them to be in a hierarchical structure. I will ponder on how Phenograph could fit in here. Meanwhile:

It's quite simple to write **any** clustering annotations into the SCE and do the usual visualizations/differential analyzes. Here's a minimal working example using the package's example data:

```
library(CATALYST)
library(Rphenograph)
library(SingleCellExperiment)

data(PBMC_fs, PBMC_panel, PBMC_md)
sce <- prepData(PBMC_fs, PBMC_panel, PBMC_md)

es <- assay(sce, "exprs")
es <- es[rowData(sce)$marker_class == "type", ]

ph_res <- phenograph(t(es), k = 30)
kids <- membership(ph_res[[2]])
kids <- factor(kids, levels = sort(unique(kids)))

sce$cluster_id <- kids
metadata(sce)$cluster_codes <- data.frame("pheno_k30" = levels(kids))

plotClusterHeatmap(sce, k = "pheno_k30")
```

Only note that I'm pretty sure`m = "pheno_k50"` or similar, specifying some lower-resolution clustering, will cause issues because Phenograph clusterings may not be hierarchically related.

Let me know if this works out or if you run into other issues! Closing this for now; but have on my list to add an example of how to integrate both `Seurat` & `Phenograph` clusterings.

**Comment by grhogg** [comment]
Thank you so much! This is wonderful!
